### ISSUE TITLE
Issue sending ETH

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#1207]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/954408500635766844

### What browsers are you seeing the problem on?

Brave

### What were you trying to do?

User tried to send ETH. Had 0.015 ETH balance in the wallet, tried to send 0.01.

### What did not work?

Dropped transactions, logs below (Gas was 60 Gwei).

Not sure if this is a bug or there is a high minimum ETH limit, but reporting for tracking purposes anyway.

A user with a comparable error message but in this case for swaps here: https://discord.com/channels/808358975287722045/888500174685614090/954735610093006918

### Version

Community Edition v0.12.1

### Relevant log output

```shell
ith a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
logger.tss:60  🐛 Tally debug @ 2022-03-18T15:16:31.629Z
logger.tss:60  ❌ Tally error @ 2022-03-18T15:16:36.715Z
logger.tss:65 Async thunk failed Error: KeyringService is already unlocked!
    at KeyringService.unlock (index.tss:158:13)
    at main.tss:903:33
    at index.jss:306:13
    at Array.map (<anonymous>)
    at Emittery.emit (index.jss:304:23)
    at async keyrings.tss:146:3
    at async utils.tss:129:9
genericLogger @ logger.tss:65
logger.tss:60  🐛 Tally debug @ 2022-03-18T15:16:44.741Z
logger.tss:60  🐛 Tally debug @ 2022-03-18T15:16:45.826Z
logger.tss:60  🐛 Tally debug @ 2022-03-18T15:16:46.503Z
logger.tss:60  🐛 Tally debug @ 2022-03-18T15:16:46.504Z
logger.tss:60  ❌ Tally error @ 2022-03-18T15:16:46.506Z
logger.tss:65 Error broadcasting transaction Object Error: intrinsic gas too low
    at WebSocketProvider._websocket.onmessage (websocket-provider.jss:77:33)
genericLogger @ logger.tss:65
websocket-provider.jss:77 Uncaught (in promise) Error: intrinsic gas too low
    at WebSocketProvider._websocket.onmessage (websocket-provider.jss:77:33)
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
logger.tss:60  ❌ Tally error @ 2022-03-18T15:17:35.873Z
logger.tss:65 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (index.jss:185:23)
    at index.jss:146:35
genericLogger @ logger.tss:65
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
logger.tss:60  ❌ Tally error @ 2022-03-18T15:19:35.874Z
logger.tss:65 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (background.js:12871:25)
    at background.js:73687:41
genericLogger @ logger.tss:65
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
logger.tss:60  ❌ Tally error @ 2022-03-18T15:21:24.066Z
logger.tss:65 Error getting block prices from BlockNative Error: failed response (requestBody=null, requestMethod="GET", url="https://api.blocknative.com/gasprices/blockprices", code=SERVER_ERROR, version=web/5.5.1)
    at Logger.makeError (background.js:12871:25)
    at Logger.throwError (background.js:12880:22)
    at background.js:73795:37
    at Generator.next (<anonymous>)
    at fulfilled (background.js:73537:28)
genericLogger @ logger.tss:65
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/b
```

**Comment by 0xDaedalus** [comment]
No longer an issue
