### ISSUE TITLE
Wallet partially loading after Chrome crash

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#1233]
### Discord Discussion Link

n/a

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Open the wallet after Chrome crashed, possibly due to the high cpu usage issue

### What did not work?

The wallet is only partially loading. The overview page is complete, but the wallet page isn't populating.

<img width="388" alt="Screen Shot 2022-03-23 at 10 12 11" src="https://user-images.githubusercontent.com/71384922/159664442-26264f40-68a0-44d4-8a03-61382d26d69d.png">
<img width="385" alt="Screen Shot 2022-03-23 at 10 12 01" src="https://user-images.githubusercontent.com/71384922/159664491-aba3eb8e-43f4-42d0-b173-16a6892e55d4.png">

### Version

Community Edition v0.12.2

### Relevant log output

```shell
logger.tss:60  🐛 Tally debug @ 2022-03-23T09:09:49.951Z
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
logger.tss:60  🪵 Tally log @ 2022-03-23T09:10:35.150Z
logger.tss:65 internal: request payload: {"id":"0","target":"tally-provider-bridge","request":{"method":"eth_accounts","params":[]}}
logger.tss:82     at chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:86839:22
    at chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:5597:22
    at Array.map (<anonymous>)
    at Emittery.emit (chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:5595:50)
logger.tss:60  🪵 Tally log @ 2022-03-23T09:10:35.155Z
logger.tss:65 internal: request payload: {"id":"1","target":"tally-provider-bridge","request":{"method":"eth_chainId","params":[]}}
logger.tss:82     at chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:86839:22
    at chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:5597:22
    at Array.map (<anonymous>)
    at Emittery.emit (chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:5595:50)
logger.tss:60  🪵 Tally log @ 2022-03-23T09:10:35.156Z
logger.tss:65 internal response: Object
logger.tss:82     at chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:86845:24
logger.tss:60  🪵 Tally log @ 2022-03-23T09:10:35.410Z
logger.tss:65 internal response: Object
logger.tss:82     at chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:86845:24
    at async Promise.all (index 0)
    at async Emittery.emit (chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:5595:11)
logger.tss:60  🪵 Tally log @ 2022-03-23T09:10:36.705Z
logger.tss:65 internal: request payload: {"id":"2","target":"tally-provider-bridge","request":{"method":"eth_accounts","params":[]}}
logger.tss:82     at chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:86839:22
    at chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:5597:22
    at Array.map (<anonymous>)
    at Emittery.emit (chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:5595:50)
logger.tss:60  🪵 Tally log @ 2022-03-23T09:10:36.845Z
logger.tss:65 internal response: Object
logger.tss:82     at chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:86845:24
    at async Promise.all (index 0)
    at async Emittery.emit (chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:5595:11)
logger.tss:60  🪵 Tally log @ 2022-03-23T09:10:36.846Z
logger.tss:65 internal: request payload: {"id":"3","target":"tally-provider-bridge","request":{"method":"eth_accounts","params":[]}}
logger.tss:82     at chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:86839:22
    at chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:5597:22
    at Array.map (<anonymous>)
    at Emittery.emit (chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:5595:50)
logger.tss:60  🪵 Tally log @ 2022-03-23T09:10:37.087Z
logger.tss:65 internal response: Object
logger.tss:82     at chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:86845:24
    at async Promise.all (index 0)
    at async Emittery.emit (chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:5595:11)
logger.tss:60  🪵 Tally log @ 2022-03-23T09:10:37.090Z
logger.tss:65 internal: request payload: {"id":"4","target":"tally-provider-bridge","request":{"method":"eth_accounts","params":[]}}
logger.tss:82     at chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:86839:22
    at chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:5597:22
    at Array.map (<anonymous>)
    at Emittery.emit (chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:5595:50)
logger.tss:60  🪵 Tally log @ 2022-03-23T09:10:37.207Z
logger.tss:65 internal response: Object
logger.tss:82     at chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:86845:24
    at async Promise.all (index 0)
    at async Emittery.emit (chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:5595:11)
logger.tss:60  🪵 Tally log @ 2022-03-23T09:10:37.330Z
logger.tss:65 internal: request payload: {"id":"5","target":"tally-provider-bridge","request":{"method":"eth_chainId","params":[]}}
logger.tss:82     at chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:86839:22
    at chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:5597:22
    at Array.map (<anonymous>)
    at Emittery.emit (chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:5595:50)
logger.tss:60  🪵 Tally log @ 2022-03-23T09:10:37.331Z
logger.tss:65 internal response: Object
logger.tss:82     at chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:86845:24
logger.tss:60  🪵 Tally log @ 2022-03-23T09:10:37.332Z
logger.tss:65 internal: request payload: {"id":"6","target":"tally-provider-bridge","request":{"method":"eth_call","params":[{"from":"0x0374c6fe0c7e2cd8299437993ad20fc905197282","to":"0x85eee30c52b0b379b046fb0f85f4f3dc3009afec","data":"0xdd62ed3e0000000000000000000000000374c6fe0c7e2cd8299437993ad20fc905197282000000000000000000000000def1c0ded9bec7f1a1670819833240f027b25eff"},"latest"]}}
logger.tss:82     at chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:86839:22
    at chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:5597:22
    at Array.map (<anonymous>)
    at Emittery.emit (chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:5595:50)
logger.tss:60  🪵 Tally log @ 2022-03-23T09:10:37.566Z
logger.tss:65 internal response: Object
logger.tss:82     at chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:86845:24
    at async Promise.all (index 0)
    at async Emittery.emit (chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:5595:11)
geturl.jss:30          GET https://api.blocknative.com/gasprices/blockprices 429
(anonymous) @ geturl.jss:30
(anonymous) @ geturl.jss:8
geturl_awaiter @ geturl.jss:4
getUrl @ geturl.jss:13
(anonymous) @ index.jss:169
fulfilled @ index.jss:5
```

**Comment by 0xDaedalus** [comment]
Stale
